### PR TITLE
[NEED TEST] zRAM + zsmalloc + zpoll update

### PR DESCRIPTION
**Pull request by Saylance**
Cherry-picked from
https://github.com/LineageOS/android_kernel_motorola_msm8960-common/commits/cm-14.1

PS.: Build error was fixed with CONFIG_PGTABLE_MAPPING=y

NEED TEST

### CODE REVIEW

**Comment by Saylance** [comment]
Currently, F2FS impl. in 4412 kernel is TOOO old, its cause unstables, and some bugs.

Thats kernel, have upstream version of F2FS, with ported stuff to 3.0.101
https://github.com/LineageOS/android_kernel_motorola_msm8960-common/commits/cm-14.1

Will cherry-pick and test it after exams.

**Comment by fourkbomb** [comment]
cool, thanks. is this working on i9100 at the moment?

**Comment by Saylance** [comment]
Here is some awesome commits from master AOSP with perfomance improve/code errors fixing:

https://android-review.googlesource.com/#/c/326024/
https://android-review.googlesource.com/#/c/326022/
https://android-review.googlesource.com/#/c/327363/
https://android-review.googlesource.com/#/c/327389/
https://android-review.googlesource.com/#/c/320879/
https://android-review.googlesource.com/#/c/331125/
https://android-review.googlesource.com/#/c/307537/

Also, last commit looks like fixing some EGLChooseConfig crush on Mali. (thought discription)

I cant merge it to linage gerrit... becouce i havent enought disk space in my computer currently to fork needed branches.
Can you push it ?

**Comment by Saylance** [comment]
Througt this topic.
My exams is fanally over, and i will compile it in different defconfigs tommorow.

Do you have Skype or Telegram for fast commun ?

**Comment by fourkbomb** [comment]
Hangouts probably works best for me - or IRC.

**Comment by fourkbomb** [comment]
BTW, have you ever seen the touchkey not work on n7000?

**Comment by Saylance** [comment]
Compiles good on N7000 with zram +zsmallock + zpool updates.
Only two errors with Wacom driver (S-Pen) and double declaration of struct. (i fixed this)

(And one more error seems goes from my toolchain, or something like that.
Fix that localy be add into include/linux/compiler.h -> #ifdef __GNUC__ -> #include <linux/bug.h>)

Now need test booting, and running apps.

**Comment by Saylance** [comment]
>BTW, have you ever seen the touchkey not work on n7000?

No, its works good on default kernel.

I saw you try many kernels for i9300
4.9, 4.4, 3.10-TIZEN, 3.10-Android, etc.
So you stop on 3.0.y (with backports) as most stable ? Another one was bad on that ?

Also, new camera HAL, that you pick from Tizen, is also worse then current ?

Thanks ;3

Also, i current don't know what to do with F2FS.
Current implementation in 4412 is very old, and not secure/stable.
But is it necessary to update it mainstream (backported to 3.0.y of course) ?

I dot trust its File System, and just use old ext4 / vfat ._.

**Comment by fourkbomb** [comment]
> 4.9, 4.4, 3.10-TIZEN, 3.10-Android, etc.
> So you stop on 3.0.y (with backports) as most stable ? Another one was bad on that ?

I'm still working on 4.9. There's a lot left to do, and I haven't had much time to work on it recently.

> Also, new camera HAL, that you pick from Tizen, is also worse then current ?

There is no new camera HAL? A Tizen HAL wouldn't work on Android, at least.

> Also, i current don't know what to do with F2FS.
> Current implementation in 4412 is very old, and not secure/stable.
> But is it necessary to update it mainstream (backported to 3.0.y of course) ?

I'm not sure. I wish we could disable it, but I guess that's not really an option. I wouldn't worry about it for now, but F2FS can definitely be another thing on the todo list.

**Comment by Saylance** [comment]
>There is no new camera HAL? 

LOL, i missed up ;D
I mean this -> (Is photos become better ?)
https://github.com/fourkbomb/android_device_samsung_smdk4412-common/commits/camera

hmmm, where do you took blobs for Exynos Mali r5p2 ?
Is it boots ? Perfomance in 3D computing increased ?
Its looks awwesome ^_^
Post some screenshots in thread, or somewere else, or some story.
Very interesting to read/see something like this.

Its so interesting, to see how you, and some people else, keep so old devices alive ;3

Have you look on my pool ?
Its compiles good now.

Its should run good, becouse i pick it from another LineageOS kernel branch.
https://github.com/LineageOS/android_kernel_motorola_msm8960-common/commits/cm-14.1

**Comment by fourkbomb** [comment]
> LOL, i missed up ;D
> I mean this -> (Is photos become better ?)
> https://github.com/fourkbomb/android_device_samsung_smdk4412-common/commits/camera

Ah, that's very old. I dunno if I'll have time to work on it, fixing the existing HAL might be easier.

> hmmm, where do you took blobs for Exynos Mali r5p2 ?
> Is it boots ? Perfomance in 3D computing increased ?
> Its looks awwesome ^_^
> Post some screenshots in thread, or somewere else, or some story.
> Very interesting to read/see something like this.

The screen is very flickery, not sure why. But GPU composition seems a lot smoother. I need to add dma-buf/ION integration to a lot of stuff (s3cfb to start with) to get overlay composition working again.

I'll test your changes when i next get a chance - probably late next week.

**Comment by Saylance** [comment]
>But GPU composition seems a lot smoother

yey, its awesome ;3
If you reach 30-35k in Antutu, its be like a half of Snapdragon 625.... its funny, LoL
(But, yeah, its so much work, to make it stable)

Then its interesting to test it in my 4210 boards - n7000 (big brother of i9100).

>I'll test your changes when i next get a chance - probably late next week.

Current pull, likes was damaged by rebase of your newer changes, so i open new.

**Pull request closed without merging**
